junit: 4.8.2

repositories:
  remote:
   - http://repo1.maven.org/maven2
   - http://download.eclipse.org/rt/eclipselink/maven.repo
   - http://github.com/realityforge/repository/raw/master

artifacts:
  javaee_api: javax:javaee-api:jar:7.0

  gwt_user: com.google.gwt:gwt-user:jar:2.6.1
  gwt_dev: com.google.gwt:gwt-dev:jar:2.6.1
  gwt_gin: com.google.gwt.inject:gin:jar:2.1.2
  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_validation_sources: javax.validation:validation-api:jar:sources:1.0.0.GA

  google_guice: com.google.inject:guice:jar:3.0
  google_guice_assistedinject: com.google.inject.extensions:guice-assistedinject:jar:3.0
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice

  javax_inject: javax.inject:javax.inject:jar:1
  javax_jsr305: com.google.code.findbugs:jsr305:jar:1.3.9

  eclipselink: org.eclipse.persistence:eclipselink:jar:2.1.0

  # HSQL for Tests
  hsqldb: org.hsqldb:hsqldb:jar:1.8.0.10
  h2db: com.h2database:h2:jar:1.3.159

  json: org.json:json:jar:20090211

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.36

  # Mocking library used
  mockito: org.mockito:mockito-all:jar:1.9.5

  jackson_core: org.codehaus.jackson:jackson-core-asl:jar:1.9.13
  jackson_mapper: org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13

  gwt_cache_filter: org.realityforge.gwt.cache-filter:gwt-cache-filter:jar:0.3

  gwt_appcache_client: org.realityforge.gwt.appcache:gwt-appcache-client:jar:1.0.4
  gwt_appcache_linker: org.realityforge.gwt.appcache:gwt-appcache-linker:jar:1.0.4
  gwt_appcache_server: org.realityforge.gwt.appcache:gwt-appcache-server:jar:1.0.4
